name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    container: circleci/ruby:2.7.1-buster-node
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_USER: sneakers
          POSTGRES_DB: testdb_test

    steps:
    - name: Prepare
      run: |
        sudo apt update
        sudo apt install git

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      env:
        PGHOST: 127.0.0.1
        PGUSER: sneakers
        RAILS_ENV: test
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake db:structure:load
        bundle exec rake db:migrate

    - name: Create PR to update image version
      if: steps.check-public-image.outputs.public_image == 'false'
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: '[BOT] Update structure.sql'
        branch: bot_update_structure_sql
        delete-branch: true
        title: '[BOT] Update structure.sql'
        body: '[BOT] Update structure.sql'

