name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    # container: circleci/ruby:2.7.1-buster-node
    services:
      db:
        image: circleci/postgres:10.11-alpine
        ports: ['5432:5432']
        env:
          POSTGRES_USER: "sneakers"
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: testdb_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Dump
      env:
        RAILS_ENV: test
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake db:structure:load
        bundle exec rake db:migrate

    - name: Create PR to update structure.sql
      id: pr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: '[BOT] Update structure.sql'
        branch: bot_update_structure_sql
        delete-branch: true
        title: '[BOT] Update structure.sql'
        body: '[BOT] Update structure.sql'

    - name: Merge PR
      env:
        PR_NUM: ${{ steps.pr.outputs.pull-request-number }}
      run: |
        curl -s \
          -X PUT \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/vincent178/test-structuresql/pulls/${PR_NUM}/merge \
          -d '{"merge_method":"squash"}'